apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvecto
  namespace: apps
  labels:
    app.kubernetes.io/name: pgvecto
    app.kubernetes.io/part-of: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pgvecto
  template:
    metadata:
      labels:
        app: pgvecto
        app.kubernetes.io/name: pgvecto
        app.kubernetes.io/part-of: immich
      annotations:
        k8up.io/backupcommand: 'sh -c ''PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall -U "$POSTGRES_USER"'''
        k8up.io/file-extension: .sql
    spec:
      containers:
        - name: pgvecto
          image: ghcr.io/immich-app/postgres:15-vectorchord0.4.3-pgvector0.8.0-pgvectors0.2.0
          ports:
            - containerPort: 5432
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_DATABASE_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_USERNAME
            - name: TZ
              value: "Europe/Moscow"
            - name: PGPORT
              value: "5432"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "750m"
              memory: "2Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-pgvecto-pvc
