apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailu-admin
    app-group: mailu
  name: mailu-admin
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mailu-admin
  template:
    metadata:
      labels:
        app: mailu-admin
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 2
      containers:
      - image: ghcr.io/mailu/admin:2024.06.47
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: QUOTA_STORAGE_URL
          value: redis://redis.apps.svc.cluster.local:6379/2
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: mailu-secrets
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              key: password
              name: mailu-secrets
        - name: ROUNDCUBE_DB_PW
          valueFrom:
            secretKeyRef:
              key: roundcube-db-password
              name: mailu-secrets
        envFrom:
        - configMapRef:
            name: mailu-envvars
        imagePullPolicy: IfNotPresent
        name: admin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 25m
            memory: 100Mi
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /dkim
          name: dkim
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mailu-admin-data-pvc
      - name: dkim
        persistentVolumeClaim:
          claimName: mailu-admin-dkim-pvc
