apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: apps
spec:
  selector:
    app: stirling-pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
