apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-pi
      tolerations:
        - key: node.hardware.arch
          operator: Equal
          value: "arm64"
          effect: NoSchedule
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.35.0
          ports:
            - containerPort: 80
          env:
            - name: ROCKET_ADDRESS
              value: 0.0.0.0
            - name: ROCKET_PORT
              value: "80"
            - name: DOMAIN
              value: "https://vw.progist.ru"
            - name: DOMAIN_ORIGIN_ALLOWLIST
              value: "https://vw.progist.ru"
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: PUSH_ENABLED
              value: "true"
            - name: PUSH_IDENTITY_URI
              value: "https://identity.bitwarden.eu"
            - name: PUSH_RELAY_URI
              value: "https://api.bitwarden.eu"
            - name: ROCKET_PROFILE
              value: "release"
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SIGNUPS_VERIFY
              value: "true"
            - name: SMTP_AUTH_MECHANISM
              value: "Plain"
            - name: SMTP_FROM
              value: "vaultwarden@progist.ru"
            - name: SMTP_FROM_NAME
              value: "Vaultwarden"
            - name: SMTP_HOST
              value: "mail.progist.ru"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_SECURITY
              value: "force_tls"
            - name: SMTP_TIMEOUT
              value: "15"
          envFrom:
            - secretRef:
                name: vaultwarden-secrets
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
