apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-external
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-strict-chain@kubernetescrd
spec:
  rules:
    - host: vw.progist.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
  tls:
    - hosts:
        - vw.progist.ru
      secretName: vaultwarden-external-tls
