apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: apps
spec:
  selector:
    app: blocky
  ports:
  - name: web-admin
    protocol: TCP
    port: 4000
    targetPort: 4000
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  type: NodePort
  externalTrafficPolicy: Local

