apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config-pv
spec:
  storageClassName: nfs-nvme-manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.4
    path: /mnt/Fast/k3s-data/jackett/config
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: apps
  annotations:
    k8up.io/backup: "true"
  labels:
    backup-level: important
spec:
  storageClassName: nfs-nvme-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  volumeName: jackett-config-pv
