apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: monitoring
spec:
  selector:
    app: adguard-exporter
  ports:
    - protocol: TCP
      port: 9618
      targetPort: 9618
  type: ClusterIP
