apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole-external
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infra-redirect-to-https@kubernetescrd,infra-guacamole-rewrite@kubernetescrd
    traefik.ingress.kubernetes.io/forwarded-headers-trusted-ip: "10.0.0.0/8,10.42.0.0/16,10.43.0.0/16"
spec:
  rules:
  - host: gua.progist.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole
            port:
              number: 8080
  tls:
  - hosts:
    - gua.progist.ru
    secretName: guacamole-external-tls
