resources:
  - storageclasses
  - renovate
  - traefik-middleware
  - xray
  - proxy
  - reloader
  - intel-device-plugin
  - minio
  - reflector

  # - traefik до лучших времён, когда потребуется 2+ нод
  # - metallb до лучших времён, когда потребуется 2+ нод
  - k8up
  - traefik-args.yaml
  - traefik-metrics-service.yaml
  - traefik-svclb-tolerations.yaml
  # nodes управляется отдельным Kustomization с prune: false
  # - nodes
