apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: apps
spec:
  selector:
    app: actual-budget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
