apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: block-metrics
  namespace: infra
spec:
  chain:
    middlewares:
      - name: metrics-path-matcher
      - name: metrics-blocker
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: metrics-path-matcher
  namespace: infra
spec:
  stripPrefix:
    prefixes:
      - "/metrics"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: metrics-blocker
  namespace: infra
spec:
  ipAllowList:
    sourceRange:
      - "127.0.0.1/32"
