resources:
  # Базовые middleware
  - redirect-to-https.yaml
  - nextcloud.yaml
  
  # Rate limiting middleware
  - ratelimit-mail.yaml
  - ratelimit-strict.yaml
  - ratelimit-media.yaml
  
  # Chain middleware (комбинации)
  - mail-chain.yaml
  - strict-chain.yaml
  - media-chain.yaml
  
  # TODO: блокировка метрик
  # - block-metrics.yaml
