apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit-strict
  namespace: infra
spec:
  rateLimit:
    average: 5
    burst: 10
    sourceCriterion:
      ipStrategy:
        depth: 0

