configMapGenerator:
  - name: gitlab-runner-values
    namespace: gitlab-runner
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - helmrelease.yaml
  - cert.yaml
