resources:
  - renovate
  - vikunja
  - memos
  - postgres
  - paperless
  - authentik
  - vaultwarden
  - guacamole
  - photoprism
  - mailu
  - immich
  - mysql
  - outline
  - cloud-dbeaver
  - nextcloud
  - frigate
