resources:
  - immich-postgres
  - storage
  - config
  - helm-release.yaml
  - service.yaml
  - ingress-external-immich.yaml
  - ingress-external-photos.yaml
  - ingress-internal.yaml

patches:
  - path: server-gpu-patch.yaml
    target:
      kind: Deployment
      name: immich-server
