configMapGenerator:
  - name: kps-values
    namespace: monitoring
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - scrapeconfigs
  - helmrelease.yaml
  - alert-manager-pv.yaml
  - grafana-pvc.yaml
  - grafana-alerts-auth.yaml
  - grafana-notifications.yaml
  - loki-datasource.yaml
  - exporters
  - rules
  - data.yaml
  - pushgateway
