configMapGenerator:
  - name: kps-values
    namespace: monitoring
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - helmrelease.yaml
  - alert-manager-pv.yaml
  - grafana-pvc.yaml
