resources:
  - alertmanager-secrets-sealed.yaml
  - kps-secrets-sealed.yaml
  - postgres-exporter-secrets-sealed.yaml
  - adguard-exporter-secrets-sealed.yaml
  - home-assistant-exporter-token-secret-sealed.yaml
  - bonchbot-secrets-sealed.yaml
  - grafana-secrets-sealed.yaml
