apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
spec:
  storageClassName: nfs-fast-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.4
    path: /mnt/Fast/k3s-data/transmission/config
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: apps
  annotations:
    k8up.io/backup: "true"
  labels:
    backup-level: important
spec:
  storageClassName: nfs-fast-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission-config-pv
