resources:
  - backups.yaml
  - config.yaml
  - configmap.yaml
  - data.yaml
  - deployment.yaml
  - ingress-internal.yaml
  - ingress-registry-internal.yaml
  - logs.yaml
  - registry.yaml
  - service.yaml
  - service-ssh.yaml
  - runner
