apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: frigate-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobName: frigate-exporter
  scrapeInterval: 15s
  metricsPath: '/api/metrics'
  scheme: HTTP
  staticConfigs:
  - targets:
    - 'frigate.apps.svc.cluster.local:5000'
    labels:
      group: 'frigate-exporter'
      service: 'frigate' 
      location: 'yolki'

  metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: '.*_bucket$'
      action: drop
    
    - sourceLabels: ["__name__"]
      regex: '.*_created$'
      action: drop
    
    - sourceLabels: ["__name__"]
      regex: '.*_(sum|count)$'
      action: drop
