apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8up-operator
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - infra
  selector:
    matchLabels:
      app.kubernetes.io/name: k8up
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
