resources:
  - external-nodes.yaml
  - gitlab.yaml
  - frigate.yaml
  - mysql.yaml
  - postgres.yaml
  - home-assistant.yaml
  - redis.yaml
  - authentik.yaml
  - adguard.yaml
  - blocky.yaml
  - jellyfin.yaml
  - bonchbot.yaml
  - traefik.yaml
  - ssl.yaml
  - k8up.yaml
