apiVersion: v1
kind: Service
metadata:
  name: ssl-exporter
  namespace: monitoring
spec:
  selector:
    app: ssl-exporter
  ports:
    - protocol: TCP
      port: 9219
      targetPort: 9219
  type: ClusterIP
