configMapGenerator:
  - name: outline-values
    namespace: apps
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - data.yaml
  - helm-release.yaml
  - backup.yaml
