resources:
  - server-data.yaml
  - server-temp.yaml
  - server-media.yaml
  - node-data.yaml
  - node-temp.yaml
  - deployment-server.yaml
  - statefulset-node.yaml
  - service.yaml
  - ingress-internal.yaml
