apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter-home
          image: prom/mysqld-exporter:v0.18.0
          args:
            - --mysqld.address=mysql.apps.svc.cluster.local:3306
            - --mysqld.username=exporter
          ports:
            - containerPort: 9104
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secrets
                  key: vps-home-password
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
        - name: mysql-exporter-spb
          image: prom/mysqld-exporter:v0.18.0
          args:
            - --mysqld.address=vps.spb:3306
            - --mysqld.username=exporter
            - --web.listen-address=0.0.0.0:9105
          ports:
            - containerPort: 9105
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secrets
                  key: vps-spb-password
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
