apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
      name: mysql-exporter-home
    - protocol: TCP
      port: 9105
      targetPort: 9105
      name: mysql-exporter-spb
  type: ClusterIP
