apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
    - protocol: TCP
      port: 9105
      targetPort: 9105
  type: ClusterIP
