apiVersion: v1
kind: Service
metadata:
  name: photoprism-mariadb
  namespace: apps
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: photoprism-mariadb
  selector:
    app: photoprism-mariadb
  type: ClusterIP
