apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
spec:
  storageClassName: hostpath-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/frigate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: apps
spec:
  storageClassName: hostpath-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: frigate-config-pv



