apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: apps
  labels:
    app: frigate
spec:
  type: NodePort
  selector:
    app: frigate
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
    - name: metrics
      port: 8971
      targetPort: 8971
      nodePort: 30971
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: 8554
      nodePort: 30554
      protocol: TCP
    - name: webrtc-tcp
      port: 8555
      nodePort: 30555
      targetPort: 8555
      protocol: TCP
    - name: webrtc-udp
      port: 8555
      nodePort: 30555
      targetPort: 8555
      protocol: UDP
    - name: rtmp
      port: 1935
      nodePort: 31935
      targetPort: 1935
      protocol: TCP



