apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster-addons
  prune: true
