apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-config
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster-addons
  prune: true
  patches:
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: coredns
          namespace: kube-system
        spec:
          template:
            spec:
              tolerations:
              - key: "node.hardware.gpu"
                operator: "Equal"
                value: "intel-igpu"
                effect: "NoSchedule"
              - key: "node.location.type"
                operator: "Equal"
                value: "remote"
                effect: "NoSchedule"
              - key: "node.role"
                operator: "Equal"
                value: "edge"
                effect: "NoSchedule"
              - key: "node.reliability"
                operator: "Equal"
                value: "low"
                effect: "NoSchedule"
              - key: "node.workload.class"
                operator: "Equal"
                value: "cctv"
                effect: "NoSchedule"
      target:
        kind: Deployment
        name: coredns
        namespace: kube-system
