resources:
  - namespaces.yaml
  - flux-system
  - sealed-secrets.yaml
  - k8up-crds.yaml
  - infra.yaml
  - ../../helm
  - cert-manager-install.yaml
  - cert-manager-issuer.yaml
  - apps.yaml
  - monitoring.yaml
  - coredns-config.yaml
  - gitlab.yaml
  - gitlab-runner.yaml
