apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-pi
      tolerations:
        - key: node.hardware.arch
          operator: Equal
          value: "arm64"
          effect: NoSchedule
      containers:
        - name: wizarr
          image: ghcr.io/wizarrrr/wizarr:v2025.12.0
          ports:
            - containerPort: 5690
          env:
            - name: TZ
              value: "Europe/Moscow"
            - name: FORCE_LANGUAGE
              value: ru
          volumeMounts:
            - name: database
              mountPath: /data/database
            - name: wizard
              mountPath: /data/wizard_steps
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: wizarr-database-pvc
        - name: wizard
          persistentVolumeClaim:
            claimName: wizarr-wizard-pvc
            