resources:
  - nfs-provisioner
  - renovate
  - filebrowser
  - vikunja
  - memos
  - mealie
  - actual-budget
  - stirling-pdf
  - prowlarr
  - wizarr
  - jellyseerr
  - homer
  - radarr
  - sonarr
  - transmission
  - postgres
  - redis
  - paperless
  - authentik
  - vaultwarden
  - jellyfin
  - immich
  - portainer
  - guacamole
  - photoprism
  - mailu
  - home-assistant
  - tautulli
  - tdarr
  - wg-easy
  - pihole
  - blocky
  - mosquitto
  - backups-pvc.yaml
  - mysql
  - outline
  - cloud-dbeaver
  - nextcloud
  - frigate
  - code-server
