resources:
  - nfs-provisioner
  - metabase
  - renovate
  - filebrowser
  - vikunja
  - memos
  - wizarr
  - jellyseerr
  - homer
  - jackett
  - radarr
  - sonarr
  - transmission
  - postgres
  - redis
  - paperless
  - authentik
  - vaultwarden
  - jellyfin
  - immich
  - portainer
  - guacamole
  - photoprism
  - mailu
  - home-assistant
  - tautulli
  - tdarr
  - wg-easy
  - pihole
  - adguard
  - mosquitto
  - backups-pvc.yaml
  - mysql
  - outline
  - cloud-dbeaver
  - nextcloud
