---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wg-easy-config-pv
spec:
  storageClassName: nfs-nvme-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/Fast/k3s-data/wg-easy/config
    server: 10.0.0.4
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-config-pvc
  namespace: apps
  labels:
    app: wg-easy
    backup-level: critical
    backup-offsite: true
spec:
  storageClassName: nfs-nvme-manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: wg-easy-config-pv
