resources:
  - pmint93.yaml
  - nfs-subdir-external-provisioner.yaml
  - authentik.yaml
  - reloader.yaml
  # - metallb.yaml
  - immich.yaml
  - prometheus.yaml
  - outline.yaml
  - gitlab-runner.yaml
  - intel-device-plugin.yaml
