resources:
  - import.yaml
  - originals.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress-internal.yaml
  - ingress-external.yaml
  - backup.yaml
  - cronjob-backup.yaml
  - mariadb
