resources:
  - backup-critical-hourly-offsite.yaml
  - backup-critical-hourly-offsite-root.yaml
  - backup-critical-hourly-root.yaml
  - backup-critical-hourly.yaml
  - backup-important-daily-offsite-root.yaml
  - backup-important-daily-offsite.yaml
  - backup-important-daily-root.yaml
  - backup-important-daily.yaml
